// =============================================================================
// FITTED: post-fit Edge Function
// =============================================================================
//
// Creates a daily post after image upload has been confirmed.
//
// FLOW:
// 1. Client requests signed upload URL (separate endpoint)
// 2. Client PUTs image directly to Storage
// 3. Client calls THIS function to create the post record
//
// INVARIANTS ENFORCED:
// 1. User is authenticated (JWT validation)
// 2. User is active member of circle (RPC validates)
// 3. One post per (user, circle, day) (RPC + DB constraint)
// 4. Image exists at expected path (Storage check)
// 5. Image path matches user ID (prevents path injection)
// 6. Post ID in path is unused (prevents replay)
//
// =============================================================================

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// =============================================================================
// TYPES
// =============================================================================

/**
 * Request payload from iOS client
 */
interface PostFitRequest {
  /** UUID of circle to post to */
  circle_id: string;

  /** IANA timezone (e.g., "America/New_York") */
  timezone: string;

  /** UUID of the post (generated by request-upload-url) */
  post_id: string;

  /** Optional image dimensions for layout optimization */
  image_width?: number;
  image_height?: number;
}

/**
 * Successful response
 */
interface PostFitResponse {
  post: {
    id: string;
    circle_id: string;
    posted_date: string; // YYYY-MM-DD
    posted_at: string; // ISO 8601
    image_url: string; // Signed delivery URL
  };
}

/**
 * Error response
 */
interface ErrorResponse {
  error: {
    code: ErrorCode;
    message?: string;
  };
}

/**
 * All possible error codes
 * Client can switch on these for UI handling
 */
type ErrorCode =
  | "AUTH_REQUIRED" // 401: No valid JWT
  | "INVALID_INPUT" // 400: Missing or malformed fields
  | "CIRCLE_NOT_FOUND" // 404: Circle doesn't exist
  | "NOT_MEMBER" // 403: User not in circle
  | "ALREADY_POSTED" // 409: Already posted today
  | "IMAGE_NOT_FOUND" // 400: Image not at expected path
  | "IMAGE_PATH_MISMATCH" // 403: Path doesn't match user
  | "POST_ID_REUSED" // 409: Post ID already exists (replay)
  | "SERVER_ERROR"; // 500: Unexpected failure

// =============================================================================
// CONFIGURATION
// =============================================================================

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const IMAGEKIT_URL_ENDPOINT = Deno.env.get("IMAGEKIT_URL_ENDPOINT")!;
const IMAGEKIT_PRIVATE_KEY = Deno.env.get("IMAGEKIT_PRIVATE_KEY")!;

/** Signed image URL TTL in seconds */
const IMAGE_URL_TTL_SECONDS = 3600; // 1 hour

/** Storage bucket name */
const STORAGE_BUCKET = "posts";

// =============================================================================
// MAIN HANDLER
// =============================================================================

Deno.serve(async (req: Request): Promise<Response> => {
  // ===========================================================================
  // CORS PREFLIGHT
  // ===========================================================================

  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 204,
      headers: corsHeaders(),
    });
  }

  // ===========================================================================
  // METHOD VALIDATION
  // ===========================================================================

  if (req.method !== "POST") {
    return errorResponse("INVALID_INPUT", 405, "Method not allowed");
  }

  try {
    // =========================================================================
    // STEP 1: AUTHENTICATE USER
    // =========================================================================
    // INVARIANT: Only authenticated users can post
    // WHY HERE: Fail fast before any other processing

    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return errorResponse("AUTH_REQUIRED", 401, "Missing authorization header");
    }

    const token = authHeader.replace("Bearer ", "");

    // Create client with user's JWT for RLS context
    const userClient = createClient(SUPABASE_URL, token, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    });

    // Validate JWT and extract user
    const {
      data: { user },
      error: authError,
    } = await userClient.auth.getUser();

    if (authError || !user) {
      return errorResponse("AUTH_REQUIRED", 401, "Invalid or expired token");
    }

    const userId = user.id;

    // =========================================================================
    // STEP 2: PARSE AND VALIDATE INPUT
    // =========================================================================
    // INVARIANT: All required fields present and well-formed
    // WHY HERE: Fail fast before expensive operations

    let body: PostFitRequest;
    try {
      body = await req.json();
    } catch {
      return errorResponse("INVALID_INPUT", 400, "Invalid JSON body");
    }

    const { circle_id, timezone, post_id, image_width, image_height } = body;

    // Validate circle_id
    if (!circle_id || !isValidUUID(circle_id)) {
      return errorResponse("INVALID_INPUT", 400, "Invalid or missing circle_id");
    }

    // Validate timezone
    if (!timezone || typeof timezone !== "string") {
      return errorResponse("INVALID_INPUT", 400, "Invalid or missing timezone");
    }

    // Validate post_id
    if (!post_id || !isValidUUID(post_id)) {
      return errorResponse("INVALID_INPUT", 400, "Invalid or missing post_id");
    }

    // =========================================================================
    // STEP 3: CHECK FOR REPLAY ATTACK
    // =========================================================================
    // INVARIANT: Post ID can only be used once
    // WHY HERE: Prevent client from reusing a post_id to overwrite/replay
    //
    // ATTACK SCENARIO:
    // 1. User posts successfully with post_id=ABC
    // 2. User deletes the post (soft delete)
    // 3. User tries to call post-fit again with post_id=ABC
    // 4. Without this check, they could create a new post pointing to old image

    const adminClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    });

    const { data: existingPost, error: checkError } = await adminClient
      .from("daily_posts")
      .select("id")
      .eq("id", post_id)
      .maybeSingle();

    if (checkError) {
      console.error("Error checking existing post:", checkError);
      return errorResponse("SERVER_ERROR", 500, "Failed to check post status");
    }

    if (existingPost) {
      // Post ID already exists (even if deleted) - this is a replay
      return errorResponse("POST_ID_REUSED", 409, "Post ID has already been used");
    }

    // =========================================================================
    // STEP 4: CONSTRUCT AND VALIDATE IMAGE PATH
    // =========================================================================
    // INVARIANT: Image path must match user ID
    // WHY HERE: Prevent user from claiming another user's image
    //
    // ATTACK SCENARIO:
    // 1. Attacker knows victim's user_id and a valid post_id
    // 2. Attacker tries to post with victim's image path
    // 3. This check ensures the path starts with the authenticated user's ID

    const imagePath = await findImageInStorage(adminClient, userId, post_id);

    if (!imagePath) {
      return errorResponse(
        "IMAGE_NOT_FOUND",
        400,
        "Image not found at expected path"
      );
    }

    // Verify path ownership (defense in depth)
    // Expected: {user_id}/{post_id}.{ext}
    if (!imagePath.startsWith(`${userId}/`)) {
      // This should never happen if Storage RLS is correct, but defense in depth
      console.error(
        `Path mismatch: expected ${userId}/*, got ${imagePath}`
      );
      return errorResponse(
        "IMAGE_PATH_MISMATCH",
        403,
        "Image path does not match user"
      );
    }

    // =========================================================================
    // STEP 5: CALL post_fit_internal RPC
    // =========================================================================
    // INVARIANT: Atomic post creation with all validations
    // WHY RPC: The RPC handles membership check, eligibility check, and
    //          atomic insert with constraint handling for race conditions
    //
    // WHAT RPC VALIDATES:
    // - User is active member of circle (NOT_MEMBER)
    // - User hasn't posted today (ALREADY_POSTED)
    // - Unique constraint (ALREADY_POSTED on race)

    const { data: postData, error: rpcError } = await adminClient.rpc(
      "post_fit_internal",
      {
        p_user_id: userId,
        p_circle_id: circle_id,
        p_timezone: timezone,
        p_image_path: imagePath,
        p_image_width: image_width ?? null,
        p_image_height: image_height ?? null,
      }
    );

    if (rpcError) {
      // Map RPC exceptions to HTTP responses
      const errorCode = parseRpcError(rpcError.message);
      const statusCode = errorCodeToStatus(errorCode);
      return errorResponse(errorCode, statusCode, rpcError.message);
    }

    // RPC returns array, get first (only) row
    const post = Array.isArray(postData) ? postData[0] : postData;

    if (!post) {
      console.error("RPC returned no data");
      return errorResponse("SERVER_ERROR", 500, "Post creation returned no data");
    }

    // =========================================================================
    // STEP 6: GENERATE SIGNED DELIVERY URL
    // =========================================================================
    // WHY: Storage is private; client needs signed URL to display image
    // TTL: 1 hour; client refreshes on app foreground

    const imageUrl = generateSignedImageUrl(imagePath, {
      width: 600,
      height: 800,
    });

    // =========================================================================
    // STEP 7: RETURN SUCCESS RESPONSE
    // =========================================================================

    const response: PostFitResponse = {
      post: {
        id: post.id,
        circle_id: post.circle_id,
        posted_date: post.posted_date,
        posted_at: post.posted_at,
        image_url: imageUrl,
      },
    };

    return new Response(JSON.stringify(response), {
      status: 201,
      headers: {
        ...corsHeaders(),
        "Content-Type": "application/json",
      },
    });
  } catch (error) {
    // =========================================================================
    // UNEXPECTED ERROR HANDLER
    // =========================================================================
    console.error("Unexpected error in post-fit:", error);
    return errorResponse("SERVER_ERROR", 500, "An unexpected error occurred");
  }
});

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Find image in storage by scanning for known extensions
 *
 * WHY: Client uploads with content-type, but we don't know the extension
 * until we check. We try common extensions in order of likelihood.
 */
async function findImageInStorage(
  client: ReturnType<typeof createClient>,
  userId: string,
  postId: string
): Promise<string | null> {
  const extensions = ["jpg", "jpeg", "heic", "png"];
  const basePath = `${userId}/${postId}`;

  for (const ext of extensions) {
    const path = `${basePath}.${ext}`;

    // Check if object exists by attempting to get its metadata
    const { data, error } = await client.storage
      .from(STORAGE_BUCKET)
      .list(userId, {
        search: `${postId}.${ext}`,
        limit: 1,
      });

    if (!error && data && data.length > 0) {
      return path;
    }
  }

  // Also try without extension (in case of MIME-based storage)
  const { data, error } = await client.storage
    .from(STORAGE_BUCKET)
    .list(userId, {
      search: postId,
      limit: 1,
    });

  if (!error && data && data.length > 0) {
    return `${userId}/${data[0].name}`;
  }

  return null;
}

/**
 * Generate signed ImageKit URL for image delivery
 *
 * Uses HMAC-SHA256 signature for URL authentication.
 * Includes transformation parameters for responsive sizing.
 */
function generateSignedImageUrl(
  imagePath: string,
  options: { width: number; height: number }
): string {
  const expiryTimestamp = Math.floor(Date.now() / 1000) + IMAGE_URL_TTL_SECONDS;

  // Transformation string for ImageKit
  const transform = `tr=w-${options.width},h-${options.height},fo-auto,c-at_max`;

  // Base URL without signature
  const baseUrl = `${IMAGEKIT_URL_ENDPOINT}/posts/${imagePath}?${transform}`;

  // Generate signature
  // ImageKit signature = HMAC-SHA256(privateKey, url + expiryTimestamp)
  const signature = generateImageKitSignature(
    `/posts/${imagePath}`,
    transform,
    expiryTimestamp
  );

  return `${baseUrl}&ik-t=${expiryTimestamp}&ik-s=${signature}`;
}

/**
 * Generate ImageKit URL signature
 *
 * SECURITY: This prevents URL tampering and guessing.
 * Signature covers: path + transforms + expiry timestamp
 */
function generateImageKitSignature(
  path: string,
  transform: string,
  expiry: number
): string {
  // ImageKit signature algorithm:
  // signature = HMAC-SHA256(privateKey, path + timestamp)
  //
  // Note: In production, use Deno's crypto API
  // This is a placeholder showing the structure

  const encoder = new TextEncoder();
  const data = encoder.encode(`${path}${expiry}`);

  // In production:
  // const key = await crypto.subtle.importKey(...)
  // const signature = await crypto.subtle.sign(...)
  // return base64url(signature)

  // Placeholder - implement with actual crypto
  return computeHmacSha256(IMAGEKIT_PRIVATE_KEY, `${path}${expiry}`);
}

/**
 * Compute HMAC-SHA256 signature
 */
function computeHmacSha256(key: string, data: string): string {
  // Implementation using Web Crypto API
  // This is async in reality but shown sync for clarity

  // In production Deno code:
  /*
  const encoder = new TextEncoder();
  const keyData = encoder.encode(key);
  const dataBytes = encoder.encode(data);

  const cryptoKey = await crypto.subtle.importKey(
    "raw",
    keyData,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );

  const signature = await crypto.subtle.sign("HMAC", cryptoKey, dataBytes);
  return base64url(new Uint8Array(signature));
  */

  // Placeholder return
  return "signature_placeholder";
}

/**
 * Validate UUID format
 */
function isValidUUID(str: string): boolean {
  const uuidRegex =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  return uuidRegex.test(str);
}

/**
 * Parse RPC error message to extract error code
 *
 * RPC raises exceptions like: RAISE EXCEPTION 'ALREADY_POSTED'
 * Supabase wraps these in error objects with message containing the code.
 */
function parseRpcError(message: string): ErrorCode {
  // RPC exceptions are formatted as the error code directly
  // or sometimes wrapped in additional text

  const knownCodes: ErrorCode[] = [
    "AUTH_REQUIRED",
    "INVALID_INPUT",
    "CIRCLE_NOT_FOUND",
    "NOT_MEMBER",
    "ALREADY_POSTED",
  ];

  for (const code of knownCodes) {
    if (message.includes(code)) {
      return code;
    }
  }

  return "SERVER_ERROR";
}

/**
 * Map error code to HTTP status
 */
function errorCodeToStatus(code: ErrorCode): number {
  const statusMap: Record<ErrorCode, number> = {
    AUTH_REQUIRED: 401,
    INVALID_INPUT: 400,
    CIRCLE_NOT_FOUND: 404,
    NOT_MEMBER: 403,
    ALREADY_POSTED: 409,
    IMAGE_NOT_FOUND: 400,
    IMAGE_PATH_MISMATCH: 403,
    POST_ID_REUSED: 409,
    SERVER_ERROR: 500,
  };
  return statusMap[code] ?? 500;
}

/**
 * Create error response
 */
function errorResponse(
  code: ErrorCode,
  status: number,
  message?: string
): Response {
  const body: ErrorResponse = {
    error: {
      code,
      ...(message && { message }),
    },
  };

  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders(),
      "Content-Type": "application/json",
    },
  });
}

/**
 * CORS headers for iOS client
 */
function corsHeaders(): Record<string, string> {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Authorization, Content-Type",
  };
}
